export const copy = {
  nav: {
    overview: "Overview",
    indexes: "Indexes",
    agents: "Agents",
    trade: "Trade",
  },
  hero: {
    badge: "Built on DeepBook Predict · Powered by AI Agents",
    title: "DeepBook Predict,",
    titleHighlight: "simplified into indexes",
    subtitle:
      'PIP wraps complex Range products into AI-managed ETFs. Say "BTC going up, medium risk" — agents handle market analysis, index construction, and rebalancing on Sui.',
    cta: "Start Trading",
    ctaSecondary: "View Agent Architecture",
    stat1: "Index Products",
    stat1Sub: "Bull · Bear · Vol · Sideway",
    stat2: "AI Agents",
    stat2Sub: "End-to-end automation",
    stat3: "User Input",
    stat3Sub: "Natural language investing",
  },
  getStarted: {
    label: "Get Started",
    title: "Invest in AI-managed indexes on Sui",
    subtitle:
      "Connect your wallet, choose an index, and let agents handle range selection, minting, and rebalancing on DeepBook Predict.",
    cta: "Open Trading",
    ctaSecondary: "Browse Indexes",
  },
  footer: {
    tagline: "Predict Index Protocol · Sui",
    copyright:
      "DeepBook Predict ranges, abstracted into AI-managed index ETFs on Sui.",
  },
  app: {
    title: "Trade Indexes",
    subtitle:
      "Supply vault liquidity or invest in AI-managed indexes on DeepBook Predict.",
    connect: "Connect wallet to trade",
    tabs: { agent: "AI Agent", vault: "Vault LP", index: "Manual", status: "Protocol" },
    manager: {
      label: "Predict Manager",
      create: "Create Manager",
      refresh: "Refresh",
      none: "No manager yet — create one or auto-create on first trade",
      hint: "Creating a manager is optional. Confirm & Execute also creates one automatically. Requires testnet SUI for gas.",
      approveInWallet: "Approve in Slush wallet…",
      createSuccess: "Predict Manager created",
    },
    vault: {
      title: "Supply Vault Liquidity",
      desc: "Supply DUSDC to the vault and receive PLP shares. Preview your transaction before confirming on chain.",
      amount: "Amount (DUSDC)",
      preview: "Preview Transaction",
      supply: "Confirm Supply",
      previewPass: "Ready to confirm",
      previewFail: "Preview failed",
      vaultValue: "Vault value",
      estShares: "Est. PLP shares",
      available: "Available withdrawal",
      maxPayout: "Max payout",
    },
    index: {
      title: "Invest in Index",
      desc: "Agents select ranges and mint your index position via predict::mint_range on DeepBook Predict.",
      select: "Select index",
      amount: "Investment (DUSDC)",
      quantity: "Range quantity",
      preview: "Preview Order",
      invest: "Confirm Investment",
      oracle: "Active oracle",
      ranges: "Selected ranges",
      mintCost: "Est. mint cost",
      redeemPayout: "Est. redeem payout",
      pipeline: "Agent pipeline",
    },
    agent: {
      title: "AI Agent Investing",
      desc: "Describe your market view in plain English. Agents analyze live oracle data, construct an index portfolio, preview the transaction, and execute on DeepBook Predict.",
      inputLabel: "Investment intent",
      placeholder: "BTC going up. Medium risk. Invest $500",
      run: "Run Agents",
      running: "Agents working…",
      execute: "Confirm & Execute",
      plan: "Agent plan",
      deposit: "Deposit",
      plpBuffer: "PLP buffer",
      simReady: "Simulation passed — ready to sign on chain",
      supportedAsset: "Supported underlying: BTC only (DeepBook Predict testnet).",
      llmOn: "LLM · {provider}",
      llmOff: "Rules engine (add GROQ_API_KEY or GEMINI_API_KEY for LLM)",
      intentSource: "Intent parsed by",
      examples: "Example prompts",
      exampleList: [
        "BTC going up. Medium risk. Invest $500",
        "Bear market, low risk, $200",
        "High volatility play, $1000",
        "Sideways range, medium risk, invest $300",
      ],
    },
    status: {
      server: "Predict server",
      trading: "Trading status",
      vaultValue: "Vault value",
      plpSupply: "PLP supply",
      package: "Package ID",
      predict: "Predict object",
    },
    tx: {
      pending: "Transaction pending…",
      success: "Transaction confirmed",
      failed: "Transaction failed",
      view: "View on explorer",
    },
  },
  common: {
    loading: "Loading…",
    refresh: "Refresh",
    connected: "Connected",
    disconnected: "Disconnected",
    connectWallet: "Connect Wallet",
  },
} as const;

export type Copy = typeof copy;
